### ISSUE TITLE
Support to private packages

### ISSUE THREAD

**Issue by luishrodg** [nachoaldamav/ultra#101]
Ultra gives an 404 error when trying to install a private github package, seems that .npmrc file is ignored by ultra. On yarn and npm works fine.

### Versions
 - Ultra: `0.7.0`
 - Node: `v16.15.0`

**Comment by nachoaldamav** [comment]
True, I completely forgot about the `.npmrc` file. I will implement it as soon as possible.

**Comment by nachoaldamav** [comment]
Tonight i'm going to create a release with this update so you can try if it works well.
In this image you can see that the packages with modified registries have the correct registry.

![image](https://user-images.githubusercontent.com/22749943/196237780-9d7fb542-13d9-4c13-8c90-a79657ea23d6.png)

**Comment by nachoaldamav** [comment]
I'm testing a package with auth (Github packages).
