### ISSUE TITLE
support set registry url? 

### ISSUE THREAD

**Issue by jeromehan** [nachoaldamav/ultra#107]
For example:
npm --registry=http://registry.npm.taobao.org

**Comment by jeromehan** [comment]
fixed

**Comment by nachoaldamav** [comment]
You can set the registry for you profile using `ultra set registry http://registry.npm.taobao.org/`.

Or for the project by creating a `.ultrarc` file.

```json
{
   "registry": "http://registry.npm.taobao.org/"
}
```
