### ISSUE TITLE
Can't install `fastify-zod`

### ISSUE THREAD

**Issue by max-programming** [nachoaldamav/ultra#126]
### Provide installed version

`[Ultra] v0.7.3 (47.05ms)`

### Current platform

Windows

### Describe the Bug

I tried running the following command
```
ultra install fastify-zod
```

And it did not install the `fastify-zod` package. Whereas `npm` successfully did it.

This is the error `ultra` gave to me **(after 26 seconds)**
![image](https://user-images.githubusercontent.com/51731966/197387935-885613c3-892e-4caf-bd7e-26b9939f73d9.png)

This is what NPM shows after installation **(after 5 seconds)**
![image](https://user-images.githubusercontent.com/51731966/197387954-0749ec20-4e4d-4e77-9985-cc8eb2448728.png)

### Expected Behavior

Expected that `fastify-zod` gets installed automatically

### Template command (if applicable)

`ultra install fastify-zod`

### To Reproduce

Run ```ultra install fastify-zod``` in a blank project

**Comment by max-programming** [comment]
Just tried installing `fastify-jwt` and again got same error

**Comment by nachoaldamav** [comment]
Looks like it's a problem with Windows, it works on WSL2 (Ubuntu)

**Comment by nachoaldamav** [comment]
> Just tried installing `fastify-jwt` and again got same error
> 
> But with an extra line ![image](https://user-images.githubusercontent.com/51731966/197388530-c1e68bb1-cf18-4a6c-b1e2-efa54bbc4f15.png)

This one may be a problem with a dependency that starts with `npm:` those are not supported yet.

**Comment by max-programming** [comment]
@nachoaldamav I just found out that `fastify-jwt` is deprecated and `@fastify/jwt` is recommended instead

**Comment by max-programming** [comment]
> Looks like it's a problem with Windows, it works on WSL2 (Ubuntu)

Does `fastify-zod` work on WSL2?

**Comment by nachoaldamav** [comment]
> > Looks like it's a problem with Windows, it works on WSL2 (Ubuntu)
> 
> Does `fastify-zod` work on WSL2?

My installation didn't fail, can you test it in a project that uses it?

**Comment by nachoaldamav** [comment]
I'm trying to fix it in this branch https://github.com/nachoaldamav/ultra/tree/fix/win-postinstall

**Comment by nachoaldamav** [comment]
Should be fixed in `v0.7.4`
`npm i ultra-pkg -g`

**Comment by max-programming** [comment]
Cool!
