### ISSUE TITLE
`init` command gets whole path in `name` field

### ISSUE THREAD

**Issue by max-programming** [nachoaldamav/ultra#134]
### Provide installed version

`[Ultra] v0.7.5 (53.67ms)`

### Current platform

Windows

### Describe the Bug

When I run `ultra init -y` command, it fills the `package.json` file's `name` field as the path of the folder instead of just the name of the folder

![image](https://user-images.githubusercontent.com/51731966/197499715-9eebea0b-d19e-4be1-9e52-7d02fa145cdc.png)

### Expected Behavior

It should fill just the name of the folder instead of the whole path

![image](https://user-images.githubusercontent.com/51731966/197499802-c27180c9-e8be-4e11-bc7b-3ea3b1a8a609.png)

### Template command (if applicable)

`ultra init -y`

### To Reproduce

Run the command: `ultra init -y`

**Comment by nachoaldamav** [comment]
Thanks for that fix!!
