### ISSUE TITLE
Create T3/Next App does not work on Windows

### ISSUE THREAD

**Issue by max-programming** [nachoaldamav/ultra#136]
### Provide installed version

`[Ultra] v0.7.5 (61.98ms)`

### Current platform

Windows

### Describe the Bug

When I run `ultra create t3-app`, it fails

![image](https://user-images.githubusercontent.com/51731966/197599297-cfd6a53a-7c17-404c-9f06-282c77faeee3.png)

### Expected Behavior

It should generate a T3 Stack app just like `npx creat-t3-app` or `yarn create t3-app`

### Template command (if applicable)

`ultra create t3-app`

### To Reproduce

`ultra create t3-app`

**Comment by max-programming** [comment]
## Update

Just tried `ultra create next-app` and that failed too

I think it has something to do with Windows

**Comment by nachoaldamav** [comment]
Looks like that the folder for the binaries in Windows is `AppData/Roaming/npm` instead of `AppData\Roaming\npm\bin`.

Should be easy to fix it.

**Comment by nachoaldamav** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/22749943/197615439-d84bd982-65b2-40f4-a235-57f673a03f13.png)

**Comment by max-programming** [comment]
Thank you @nachoaldamav!
Can I upgrade and use with the latest version or will it be released later?

**Comment by nachoaldamav** [comment]
> Thank you @nachoaldamav!
> Can I upgrade and use with the latest version or will it be released later?

I've released it a few minutes ago hahaha
