### ISSUE TITLE
Failed to generate lockfile

### ISSUE THREAD

**Issue by max-programming** [nachoaldamav/ultra#149]
### Provide installed version

`[Ultra] v0.7.15 (58.93ms)`

### Provide Node.js version

`v16.17.1`

### Current platform

Windows

### Describe the Bug

After installing a package, it fails to generate the `ultra.lock` file

```
file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/ultra-pkg/build/utils/genLockfile.js:14
        const { name , version , integrity , path , tarball  } = parsed["ultra:self"];
                ^

TypeError: Cannot destructure property 'name' of 'parsed.ultra:self' as it is undefined.
    at file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/ultra-pkg/build/utils/genLockfile.js:14:17
    at Array.map (<anonymous>)
    at genLock (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/ultra-pkg/build/utils/genLockfile.js:11:24)
    at install (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/ultra-pkg/build/commands/install.js:201:9)
```

![image](https://user-images.githubusercontent.com/51731966/207270872-6a8bfab7-eb58-47af-a099-5e5a24e7563f.png)

### Expected Behavior

It should generate a lockfile

### To Reproduce

Run the command `ultra i express`.

**Comment by nachoaldamav** [comment]
Try with the version `v0.7.16`
